# Generated by Django 3.0.4 on 2020-07-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='部署名')),
                ('branch', models.IntegerField(blank=True, choices=[(10, '本社'), (20, '滋賀支店'), (30, '舞鶴支店')], null=True, verbose_name='支店')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, max_length=5000, null=True, verbose_name='summary')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('startDate', models.CharField(blank=True, max_length=255, null=True, verbose_name='startDate')),
                ('endDate', models.CharField(blank=True, max_length=255, null=True, verbose_name='endDate')),
                ('iCalUID', models.TextField(blank=True, max_length=5000, null=True, verbose_name='iCalUID')),
                ('etag', models.CharField(blank=True, max_length=255, null=True, verbose_name='etag')),
                ('googleEventId', models.CharField(blank=True, max_length=255, null=True, verbose_name='etag')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=255, verbose_name='code')),
                ('post_time', models.CharField(max_length=255, verbose_name='postTime')),
                ('message', models.TextField(blank=True, max_length=50000, verbose_name='message')),
                ('slack_comment_id', models.CharField(blank=True, max_length=255, verbose_name='message')),
                ('encode_time', models.DateTimeField(blank=True, null=True, verbose_name='postTimes')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='座席番号')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='社員Id')),
                ('eventDate', models.DateField(blank=True, max_length=255, null=True, verbose_name='eventDate')),
            ],
        ),
        migrations.CreateModel(
            name='SlackMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名前')),
                ('slack_name', models.CharField(max_length=255, verbose_name='slack名')),
                ('slack_id', models.CharField(max_length=255, verbose_name='slackId')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='ステータス')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='投稿時間')),
                ('account', models.CharField(blank=True, max_length=255, null=True, verbose_name='アカウント')),
                ('flg_seat', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='座席不要フラグ')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_name', to='slack.Department', verbose_name='部署')),
            ],
        ),
    ]
